config/routes.rb
Unanidate::Application.routes.draw do

  resources :events do
    member do
      put 'select/:option_id', :action => :select, :as => :select
      put 'unselect', :action => :unselect, :as => :unselect
    end
  end

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :title, :selected_option_id, :options_attributes

  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
  belongs_to :selected_option, class_name: Option

  validates :title, presence: true

  def select(option_id)
    self.selected_option = options.find(option_id)
  end

  def unselect
    self.selected_option = nil
  end

end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :datetime
  belongs_to :event

  validates_datetime :datetime

  def selected?
    return false unless event
    id == event.selected_option_id
  end

  def to_s
    datetime.strftime("%A %-d %B @ %l:%M %p")
  end

  def date
    datetime.strftime("%A %-d %B")
  end

  def time
    datetime.strftime("%l:%M %p")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :load_event, except: [:index, :create, :new]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Event was successfully created.'
        end
        format.json do
          render json: @event, status: :created, location: @event
        end
      else
        format.html do
          render "new"
        end
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html do
          redirect_to @event, notice: 'Event was successfully updated.'
        end
        format.json do
          head :no_content
        end
      else
        format.html do
          render "edit"
        end
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  # PUT /events/1/select/2
  # PUT /events/1/select/2.json
  def select
    @event.select(params[:option_id])

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Option was successfully selected.'
        end
        format.json do
          head :no_content
        end
      else
        format.html do
          render "show"
        end
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PUT /events/1/unselect
  # PUT /events/1/unselect
  def unselect
    @event.unselect

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Option was successfully unselected.'
        end
        format.json do
          head :no_content
        end
      else
        format.html do
          render "show"
        end
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def load_event
    @event = Event.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::XHTML.new(
      filter_html: true,
      safe_links_only: true,
      hard_wrap: true
    )
    markdown = Redcarpet::Markdown.new(
      renderer,
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      autolink: true,
      strikethrough: true,
    )
    markdown.render(text).html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper

  # Ref: http://stackoverflow.com/questions/2678009/how-to-add-and-remove-nested-model-fields-dynamically-using-haml-and-formtastic

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new

    fields = f.fields_for(
      association,
      new_object,
      child_index: "new_#{association}"
    ) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    button_tag(
      name,
      type: :button,
      class: "add-option-btn",
      onClick: "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"
    )
  end
end

app/views/events/_form.html.haml
-# TODO: Make this form work as functionally as the version pre-twitter-bootstrap!
= form_for @event, html: { class: 'form-horizontal' } do |f|
  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'text_field span7'
  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, class: 'text_area span7'
  = fields_for :options do |option_fields|
    = render "option_fields", f: option_fields
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), events_path, class: 'btn'

app/views/events/_option_fields.html.haml
.control-group
  = f.label :datetime, class: 'control-label'
  .controls
    .input-append
      = f.text_field :datetime, label: "Date and time", class: "span7", type: "datetime"
      %span.btn>
        %i.icon-calendar.datetimepicker
      %p.help-block
        -# TODO: This functionality won't work until Chronic gem is used
        You can use English! &nbsp; e.g. Next Monday at 7:30 PM

app/views/events/edit.html.haml
.page-header
  %h1 Edit Event
= render "form"

app/views/events/index.html.haml
.page-header
  %h1 Events

#eventsAccordion.accordion
  - @events.each do |event|
    .accordion-group
      .accordion-heading
        %a{href: "#collapse-#{event.id}", class: "accordion-toggle", data: {parent: "#eventsAccordion", toggle: "collapse"}}
          = event.title
          %span.summary
            - date = event.selected_option
            = " - #{date}" if date
            = " - Unconfirmed" unless date
      .accordion-body.collapse{id: "collapse-#{event.id}"}
        .accordion-inner
          = markdown(event.description)
          = link_to "Show", event_path(event), class: 'btn btn-small'
          = link_to t('.edit', default: t("helpers.links.edit")), edit_event_path(event), class: 'btn btn-small'
          = link_to t('.destroy', default: t("helpers.links.destroy")), event_path(event), method: :delete, data: {confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?'))}, class: 'btn btn-small btn-danger'

= link_to t('.new', default: t("helpers.links.new")), new_event_path, class: 'btn btn-primary'

app/views/events/new.html.haml
.page-header
  %h1 New Event
= render "form"

app/views/events/show.html.haml
.page-header
  %h1#event-title= @event.title

%ul.unstyled
  %li
    %i.icon-user{title: "Owner"}
    Steven Occhipinti
  - if @event.selected_option
    %li
      %i.icon-calendar{title: "Date"}
      = @event.selected_option.date
    %li
      %i.icon-time{title: "Time"}
      = @event.selected_option.time

#description.well
  = markdown(@event.description)

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Date
      %th Time
      %th Current Votes
      %th Actions
  %tbody
    - @event.options.each do |o|
      %tr
        %td= o.date
        %td= o.time
        %td
          -# TODO: Display votes and make the highest vote count "badge-success"
          %span.badge{class: "#{o == @event.options.first ? "badge-success" : ""}"}
            = Random.rand(0..10)
          -# TODO: After the badge should probably be thumbnails of the voters
        %td
          - if @event.selected_option
            = link_to "Un-select", unselect_event_path(@event.id), class: 'btn btn-small', method: :put if o.selected?
          - else
            = link_to "Vote", :root, class: 'btn btn-primary btn-small'
            = link_to "Select", select_event_path(@event.id, o.id), class: 'btn btn-success btn-small', method: :put

.form-actions
  = link_to t('.back', default: t("helpers.links.back")), events_path, class: 'btn'
  = link_to t('.edit', default: t("helpers.links.edit")), edit_event_path(@event), class: 'btn'
  = link_to t('.destroy', default: t("helpers.links.destroy")), event_path(@event), method: "delete", data: {confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?'))}, class: 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Unanidate"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", media: "all"
    %link(href="favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")
    = yield(:head)

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Unanidate", root_path, class: "brand"
          .container.nav-collapse
            %ul.nav
              %li= link_to "New event", new_event_path
              %li= link_to "My events", events_path

    .container

      .content
        .row
          .span12
            = yield

      %footer
        %p= "&copy; StevenOcchipinti #{Time.now.year}".html_safe
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"